spring:
  application:
    name: redis-lingpai-annotation
  data:
    redis:
      host: 1.95.47.33
      password: 123456
      port: 6379
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
task:
  time: 10000
  size: 10